### ISSUE TITLE
Setting FPS limit higher than 60 has no effect

### ISSUE THREAD

**Issue by geNAZt** [melonjs/melonJS#1002]
If you are submitting a bug report, please respect the below template :

#### OS platform / Browser  
Windows 10 / Edge, Firefox, Chrome

#### melonJS version 
8.0.0 / master

#### Bug description  
Setting me.sys.fps = 120 shows target FPS 120 in debug panel but does not result in actual more FPS even when the draw loop would allow it (draw update < 16.6ms)

#### Steps to reproduce the bug
Visit https://doublechins.genazt.me/ and press S for the debug panel to open. It should run at 120 FPS but it doesn't

**Comment by obiot** [comment]
so I'm not really able to test it on my side as I have no combination of machine or monitor that allows me to use a 120Hz display rate, but after inspection, there is no hardcoded limit in the current implementation that prevent the main loop (when using `requestAnimationFrame` on modern hardware) to run at 120fps. Also setting it down to 30fps for example correctly works which kind of shows that the logic behind is properly working (so higher should work if supported)

couple of comments :
- as per the [standard](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame), the number of callbacks is usually 60 times per second, but will generally match the display refresh rate in most web browsers as per W3C recommendation, so this cannot be guaranteed on all browser machines (just something to keep in mind)
- I did actually find one hard limit, but this won't be really useful as this only applies to old browser implementation that do not support `requestAnimationFrame` and where we revert back on a `setTimeout` based polyfill ([but it has been supported by all major browser since a long time now](https://caniuse.com/#feat=requestanimationframe))
- you can still use a different frame rate for the update loop and the draw loop, actually in my test I used `me.sys.fps = me.sys.updatesPerSecond = 120;` to set both at 120fps, but since it did not impact the draw framerate i still ended up with a 120fps update loop but a 60fps display (try it you will see the smoothness experience is the same as a 120fps refresh)

so I will close this ticket, nothing more we can do I believe here.
