### ISSUE TITLE
Space Invaders error: TypeError: r._absPos is undefined

### ISSUE THREAD

**Issue by waynetran** [melonjs/melonJS#1007]
If you are submitting a bug report, please respect the below template :

#### OS platform / Browser  
e.g. Mac OS 10.15.5 / Firefox 77.0.1 / Chrome 83.0.4103.116
 
#### melonJS version 
7.1.1

#### Bug description  
After finishing the space invaders tutorial with the last line being resetting the playScreen on the win condition, the game crashes with the error below.

#### Steps to reproduce the bug
```
update : function (time) {
    if (this.children.length === 0 && this.createdEnemies) {
       //This line causes the error.
        game.playScreen.reset();  
    }
    this._super(me.Container, "update", [time]);
    this.updateChildBounds();
}
```
#### Console log Extract 
Firefox Console:
```
TypeError: r._absPos is undefined melonjs.min.js:14:72330
    update https://cdn.jsdelivr.net/npm/melonjs@7.1.1/dist/melonjs.min.js:14
    update https://cdn.jsdelivr.net/npm/melonjs@7.1.1/dist/melonjs.min.js:14
    patchSystemFn https://cdn.jsdelivr.net/npm/melonjs@7.1.1/plugins/debug/debugPanel.js:365
    value https://cdn.jsdelivr.net/npm/melonjs@7.1.1/dist/melonjs.min.js:36
    u https://cdn.jsdelivr.net/npm/melonjs@7.1.1/dist/melonjs.min.js:14
```
Chrome Console:
```
Uncaught TypeError: Cannot read property 'setV' of undefined
    at s.update (melonjs.min.js:14)
    at Object.e.update [as _patched] (melonjs.min.js:14)
    at Object.<anonymous> (debugPanel.js:365)
    at Object.update (melonjs.min.js:36)
    at u (melonjs.min.js:14)
```

**Comment by obiot** [comment]
thanks, will check it out.

**Comment by obiot** [comment]
hi, so ok first of all, that tutorial definitely some update to better use all the improvements we brought since version 6.0

the main issue here is a race condition, where the game is trying to remove/reset the enemy object container, while the main game loop is updating it (so it triggers an exception like here above as part of the object have been destroyed already).

a proper solution is to actually use the [onChildChange](http://melonjs.github.io/melonJS/docs/me.Container.html#onChildChange) callback to actually update the container bounds only when a child is added or removed, and from them check if the amount of children reach 0 and then if yes end the game.

see below for the required changes :
https://github.com/melonjs/tutorial-space-invaders/commit/43d4b7c2a1124d690a14b639745c51ea795e5560#diff-55e845ee3be24edb5008664636b102d0

let me know, but it should be working now with this changes.

**Comment by waynetran** [comment]
Awesome! Works.
Thanks.
