### ISSUE TITLE
Canvas width and height become 0 after switching to another intent or app becomes inactive, and cannot be reinitialised

### ISSUE THREAD

**Issue by siauderman** [melonjs/melonJS#1082]
Dear Olivier,

I notice that when the app launches another new intent on Android (e.g. https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin) the canvas width and height become 0. This also happens if for example on Windows you switch to another app for some time and then switch back. As a result, after this happens nothing can be drawn and even calling me.video.init again does not work in reinitialising the canvas / WebGL.

I've also tried to call resize after this happens, but it doesn't work either.

**Comment by obiot** [comment]
Hi @siauderman I have no idea how to reproduce this one to be honest (I'm lazy to setup a whole project with that plugin to try it out, and we have no issues with project packaged with Cordova on android), but there were a few regression fixed in the 1.5.x versions around resizing, so if you update to the very last one (which is 1.6.1 as I write this) I believe this should hopefully address it. if you could confirm that would be great !

**Comment by obiot** [comment]
closing this one, will reopen if it is confirmed to be still present in the latest 10.9 version or higher
