### ISSUE TITLE
Support programmatically generated maps

### ISSUE THREAD

**Issue by hmd-ai** [melonjs/melonJS#1165]
Thanks for making melonJS!
**Describe the solution you'd like**

I would like to create a programmatically generated map (to create an open infinite world effect).
One hack might be to create multiple levels in the code and load one after another seamlessly, 
but I believe loading a new level would cause a fade to black effect.

Is there any way to achieve this currently? 

**Describe alternatives you've considered**
- Might be related to https://github.com/melonjs/melonJS/issues/1122

**Comment by hmd-ai** [comment]
The first step would probably be to support `wangset` element in the tmx file: e.g.:


```
  <wangsets>
   <wangset name="Unnamed Set" type="mixed" tile="-1">
    <wangcolor name="ground" color="#ff7700" tile="0" probability="1"/>
    <wangtile tileid="0" wangid="0,0,0,4,0,0,0,0"/>
    <wangtile tileid="1" wangid="0,0,0,4,4,4,0,0"/>
    <wangtile tileid="2" wangid="0,0,0,0,0,4,0,0"/>
    <wangtile tileid="16" wangid="0,4,4,4,0,0,0,0"/>
    <wangtile tileid="17" wangid="4,4,4,4,4,4,4,4"/>
....
   </wangset>
  </wangsets>
```

**Comment by obiot** [comment]
I think the answer is both more simple and more complex than just wang tiles.

Wang tiles is just a (automatic) way to more easily fill a large area of terrain, instead of doing everything manually, but when it comes to programmatically generate a map, it does not actually matter, and you can programmatically "paint" your terrain with regular tileset/tiles.

Also are you really looking at creating an open world like game (which at the end is finite), or really a infinite randomly/procedurally generated map ?

then few points to consider :
1. the most common way to programmatically generate a map, is to create a JSON object map (see https://doc.mapeditor.org/en/stable/reference/json-map-format/), this is what is usually done with dynamically (server side) generated map, and those can be loaded even as based 64 encoded from the client side.
2. for a open world, but finite map, you can just design a massive map, and load it in melonJS. It will only render the portion visible on screen, so beside consuming more memory for a bigger array of data, it will not impact the visual or performances of the game
3. for a infinite runner, or similar concept, you don't need a map, you can just add new object to the screen and move them around the players.
4. the fading effect is actually optional, if you don't specify anything the map will just be replace instantaneously. you can also definitely use this  with a bridge or whatever thing as a trick or joint during 2 portions of maps.
5.  for Infinite maps, sadly though, we don't support infinite map in melonJS (see https://github.com/melonjs/melonJS/discussions/1048)

hope this helps for now, unless you really need number 5 !

**Comment by hmd-ai** [comment]
Thanks @obiot for the response.

I think a benefit of the wang tiles, is that it makes choosing the tiles from the tileset easier, since just choosing one at random might not make sense depending on what is around that tile. One way to work around that is to manually select a number of tiles in the tile set that can be next to each other, but this is effectively what the wang tiles spec provide (with great support in the tiled map editor as well).

To clarify I'm interested in an infinite procedurally generated map, but the map has to visually make sense, in other words it can't be a random selection from the tileset. Is there a way to achieve this at the moment?

**Comment by obiot** [comment]
I can definitely look at adding at least wangset tiles in the next few days, support, it should not be that complicated.

So for now, you can just maybe make yourself familiar with melonJS using a procedurally generate map with a "traditional tileset", and then update your map once wangset was added ?

as a start, I just refreshed/updated the map loader example to the latest melonJS 2 version, but as you can see now wangset tiles/terrain map yet:
https://melonjs.github.io/examples/tiled_example_loader/

**Comment by obiot** [comment]
I just realized while looking at it, that melonJS can already parse and render wangset based tilemaps.

the thing is that wangset definition are using (only) when generating the map, but in melonJS we just parse and render the map built with the wangset tiles, so there is really nothing to add in melonJS, except maybe parsing the wangset tiles, but that would be purely for information only as we would not need to do anything with it.

I update the desert map in the map loader example with the latest [wangset based map](https://github.com/mapeditor/tiled/blob/master/examples/desert.tsx), and as you can see it just works fine:
https://melonjs.github.io/examples/tiled_example_loader/
> make sure to select "desert" in the top drop down list, and move the screen by scrolling up or down if the the map does not refresh properly

**Comment by obiot** [comment]
@hmd-ai ok so with the latest commit, and the corresponding next 14.4 release, melonJS can now properly parse and render finite and infinite maps, made with or without wangset ! I'll do some more testing and publish it over the weekend.

in the meantime, here is a build if you want to test it :
[melonjs.14.4.0-beta.zip](https://github.com/melonjs/melonJS/files/10358713/melonjs.14.4.0-beta.zip)

and I'm closing this ticket :)

**Comment by raquelhortab** [comment]
Hi! I don't know anything about game dev nor map creation and I am trying to generate a map programmatically. The thing is that when looking at the files generated by Tiled (either JSON or TMX) I see that the layers are encoded so I cannot see how I could generate something similar myself. I did not find an option in Tiled to export it without it being encoded. 
Any help is appreciated, thanks!

**Comment by obiot** [comment]
the easiest is to export in JSON format (https://doc.mapeditor.org/en/stable/manual/export-generic/) , and then use CSV as the Tile Layer Format in Tiled.
<img width="446" alt="Screenshot 2024-09-18 at 8 45 22 AM" src="https://github.com/user-attachments/assets/c835d76a-4166-4732-9627-116fbe4e9960">
