### ISSUE TITLE
this.body is pointing to Dom type when using Typescript Boilerplate

### ISSUE THREAD

**Issue by brunofunnie** [melonjs/melonJS#1199]
I notice that when using the Typescript boilerplate and when setting a new Body it refers to the DOM instead of MelonJS.

The code:
![image](https://github.com/melonjs/melonJS/assets/5279392/f136ecbe-eb69-4a7b-9a2d-be05d7b897d8)

On VSCODE shows:
![image](https://github.com/melonjs/melonJS/assets/5279392/0ac57261-d4d8-4bc6-975c-e6b17a49752f)

Typescript reference of Body:
![image](https://github.com/melonjs/melonJS/assets/5279392/e1a9d3b7-d0e1-4010-9647-5104cf2bd81e)

Using a just cloned Typescript Boilerplate and following the https://codemonkey.club/getting-started-with-melonjs/

**Comment by obiot** [comment]
thank you very much for the report, we will look into it. 

We are still in the process of providing proper typings for melonJS, please do share if you find any other issues. In the mean time, you can use `@ts-ignore` to remove the warning/error report in VSC.

**Comment by muyaszed** [comment]
I have a fix for this, just need the suitable replacement name for `Body` class. Atm I'm using `BodyObject` for it. the Method will still be using `body`

**Comment by muyaszed** [comment]
Do I need to commit the updated Doc as well?

**Comment by daniel-centore** [comment]
For now I'm working around this with:

```typescript
import { Body } from "melonjs";

const body = this.body as unknown as Body;
//  use `body` wherever needed
```

Would be great to get a real fix for it!

**Comment by obiot** [comment]
me too It has been bothering me, but I really don't know how to fix it properly (I mean without renaming the object!)

**Comment by obiot** [comment]
This one should be fix now, I just simply "tricked" it by importing Body within the Renderable class (together with referencing the Body class, so that the bundler doesnt complain).

I found out another issue is that rollup does not always respect the right module order in the bundle if I add import/reference for Application. Another issue, but at least the Body one should be resolved now.

I will leave this one open until the next 17.1 version is released and the fix confirmed to work.

**Comment by obiot** [comment]
17.1.0 released, if you guys could confirm it's now correct from your side as well, thanks !

**Comment by obiot** [comment]
closing this one, working on my side.
