### ISSUE TITLE
withCredentials does not get set in fetch calls

### ISSUE THREAD

**Issue by B0sh** [melonjs/melonJS#1220]
**Describe the bug**

I upgraded to melonjs 16 and noticed that the new fetch update wasn't sending cookies along with the requests which is used in my setup. I tried to make a PR for this but it seems deeper than I was able to figure out.

**To Reproduce**

I setup `loader.withCredentials = true;`, but noticed my cookies still weren't included.

**Expected behavior**

https://github.com/melonjs/melonJS/blob/b7df427064061b801c1982e4baf3eaa9eafeb2a8/src/loader/parsers/fetchdata.js#L17-L26

If I add a console log before the promise like `console.log(withCredentials)` it always is set to false. However I when I tried `console.log(loader.withCredentials);` it was able to read the value correctly. I'm not super familiar with es6 modules so I didn't want to make a PR that just updated the settings here to reference loader directly, but that solution does work. The other settings probably aren't working too, although I didn't test them. Once this gets figured out I'll be happy to update to the fetch version!

**Screenshots**

**Live Example**

**Device (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - melonJS Version: 

**Additional context**

**Comment by obiot** [comment]
oh interesting, thanks for reporting it !

**Comment by obiot** [comment]
Hi, so I fixed the issue. The trick to use `loader.withCredentials` works indeed but the problem is that it's creating cyclic dependencies. So I did reorganised the source code, but then because you cannot modify exported properties in es6 (this was overlooked when we migrated from es5 to es6), I added a `setOption()` method that allows to set custom settings for the loader. 

```javascript
 // Set the crossOrigin attribute to "anonymous"
 me.loader.setOptions({ crossOrigin: "anonymous" });
 
 // Enable the nocache mechanism
 me.loader.setOptions({ nocache: true });

 // Enable withCredentials
 me.loader.setOptions({ withCredentials: true });
```

this also breaks compatibility with previous version, so I also had to increase the major version (now it's 17.0)

Before I release it, would you be able to give it a test, the latest distribution file is here :
https://github.com/melonjs/melonJS/tree/master/dist

**Comment by B0sh** [comment]
Thank you! Just tried it this morning and it does work. I figured the hack with using loader itself wouldn't work out, glad you were able to resolve it quickly
