### ISSUE TITLE
Falling Bug

### ISSUE THREAD

**Issue by kosinix** [melonjs/melonJS#16]
Hi,

First, this is a great javascript engine. I ported an old platform game I made in flash. However, there is one critical bug when falling from high places. For example, when jumping from high platform the hero goes through a solid tile. My theory is this has something to do with the acceleration of the fall greater than the height of the solid tile, as I encountered this kind of bug with my flash engine from long time ago. Just hoping you could check this bug, that would be really cool.

thanks! Really nice game engine.

**Comment by obiot** [comment]
ok, I'm closing this one for the following reasons :
- the problem was only visible in earlier version of melonJS, and the cap to `maxVel` is "hiding" the issue
- the ticket is redundant with other tickets were we discussed about having a better physic implementation : #235 #285 #588 , in the sense that the later 3 will not have such issue.
