### ISSUE TITLE
Automatic collision detection and response

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#574]
as discussed here :
https://github.com/melonjs/melonJS/commit/d5dc2aab4e640eafc8e80e634bd1e68ea37733db

Implement a new collision method that will perform a complete collision check with responses and callbacks against every entity in a single call, and that will be performed by melonJS once per frame. 

This would replace the check method entirely, and user code would not be responsible for, nor care anymore on how to perform collision detection. 

A one-shot collision check will also be faster, as it will entirely eliminate duplicate object-pair collision checks. See also this thread: https://groups.google.com/d/msg/melonjs/7mIUAI1U6K8/FTz9Ui7qQgEJ

**Comment by parasyte** [comment]
Putting this here before I forget: In addition to the items listed above (double collision handling, multiple collision response phases, optimizations, etc.) there's an issue with position and velocity correction using a single response object when the colliding entities are both moving; `me.Body.respondToCollision` expects objA to be moving and objB to be not moving. This will probably be fixed by #588 because handling `mass` requires that the velocity of both entities is taken into consideration.
