### ISSUE TITLE
Docs Internationalisation

### ISSUE THREAD

**Issue by ellisonleao** [melonjs/melonJS#586]
Hey guys, i think it's a good idea to make the docs available in many other languages. Perhaps we could find some automated tool like http://formatjs.io/ to create the translations. I know a very good service called http://transifex.com/ , which brings a collaboration tool to help translate texts to different languages. What do you guys think?

**Comment by Ascheere** [comment]
I agree with agmcleod. I work with a lot of localization at work and translating something automatically can cause a lot of errors and can in some cases even be a legal issue.

**Comment by obiot** [comment]
Transifex is a collaborative translation platform (Tiled is using it for example), but I'm having some hard time to see how to integrate this into our documentation process. 

And about the potential legal issue mention, I think that with the MIT License, we are covered :)
`HE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`

**Comment by obiot** [comment]
Internationalization workflow : 

https://www.npmjs.com/package/jsdoc-i18n

https://github.com/AlmirKadric-Published/jsdoc-i18n
