### ISSUE TITLE
Physics improvements: mass and friction

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#588]
To go alongside #565 it would be nice to have some additional physics properties, like mass and friction.
- Mass will allow bodies to push one another. World bodies will typically have `mass = Infinity` so they cannot be pushed.
- Friction is trickier to define; we already have support for "friction" which is closer to air resistance (drag). E.g. A physics body that has velocity applied once will eventually come to a stop (assuming gravity is not overpowering the resistance). What we actually need is friction between bodies, which is calculated using a friction coefficient between two bodies.

**Comment by obiot** [comment]
following the last commit with the PE tool (ticket #413), i would actually propose the following properties

`me.Body.density`: or mass, a measurement of how tightly matter is crammed together. for the entity/body to be static (ie: immovable) then the density should be set to 0, essentially making it infinitely dense. 

`me.Body.friction`: the force resisting the relative motion of solid surfaces, fluid layers, and material elements sliding against each other.

`me.Body.bounce` :  or restitution, to define the "bounciness" of an object when colliding with another object

Last but not least, shall we update a bit the 'me.sys.gravity' property ? move it somewhere else, and change it to a vector so that we can define a different gravity on the two axis ?

**Comment by parasyte** [comment]
Some corrections, I think:

Mass is more about weight; how heavy a body is. With the value `Infinity`, no other body can apply a force to it. With values that are `<= 0`, it would do crazy and unexpected things! :smiley:

The forces are applied as part of collision resolution. As today, the force is equally applied to both bodies: https://github.com/melonjs/melonJS/blob/82fd991b03b89d735c436674a904c92500cfb99b/src/physics/collision.js#L505-L510 and https://github.com/melonjs/melonJS/blob/82fd991b03b89d735c436674a904c92500cfb99b/src/physics/body.js#L300-L303 To add `mass`, the response overlap needs to be proportional to the ratio between both body's masses.

The ratio calculation is something like this:

```javascript
var massA = objA.body.mass,
    massB = objB.body.mass,
    combinedMass = massA + massB,
    responseA = response.overlapV.scale((massA / combinedMass) || 0),
    responseB = response.overlapV.scale((massB / combinedMass) || 0);
```

If I'm not mistaken, those two response variables can be passed to `body.respondToCollision` for the respective body, et violà!

---

Similarly, bounce applies to the body's velocity in the `respondToCollision` function. Today they are treated as having 0 bounce. Which is not true of the physical world. ;) It works for platformer physics, though! A "normal" bounce would apply the "equal and opposite reaction" from Newton's Third Law by changing the sign of the velocity without reduction.

So it seems to me the easiest implementation is negating the velocity and then scaling by the value of `bounce`.

```javascript
this.vel.x = (-this.vel.x * this.bounce) || 0;
```

**Comment by obiot** [comment]
so mass and density are two different things ? is this also what you are saying ?

**Comment by parasyte** [comment]
In physics both words mean the same === weight. :)

**Comment by agmcleod** [comment]
Hmm? Mass and weight can vary from one another. Example, i would weigh less on the moon, but have the same mass.

**Comment by parasyte** [comment]
Ah yes, my mistake. I only mean weight as relative to other bodies. The code above provides an example, as only ratio between colliding bodies is used to solve the collision.

The ratio between our weights is the same on earth and the moon. ;)

**Comment by Giwayume** [comment]
I'm running into an issue that I think could be fixed with this...

Basically the player is not able to walk past enemies in my game (platformer), making enemies semi-solid objects (they push the payer back on x axis collision, ignore y axis collision).

It all works fine and dandy until the enemy pushes the player up against a WORLD_SHAPE. Because the WORLD_SHAPE was placed in the level editor first, its collision is calculated before the player/enemy collision. Thus the player/enemy collision offset wins and the player is pushed through the WORLD_SHAPE. 

I want the opposite, all of the WORLD_SHAPE collision calculated last. That would be a simple solution, but I think this would also solve my problem.

**Comment by obiot** [comment]
more improvements to come later, but as for now this one can be closed
