### ISSUE TITLE
Tiled Layer Pre-Render Problem

### ISSUE THREAD

**Issue by aaschmitz** [melonjs/melonJS#661]
With the last 2.1 dev version, using a Tiled Layer with pre-render=true (and video renderer=me.video.CANVAS), the console log:

Uncaught TypeError: undefined is not a function melonJS-2.1.0.js:18997 

Thanks!

**Comment by obiot** [comment]
i thought it was an easy fix, but it's not !

the issue is that the `preRender` mode relies on function like `me.Tileset.drawTile()` to draw all the tiles on an offscreen canvas, but with all the changes we made, the `drawTile()` function now only accepts a renderer as parameter.

I would suggest you disable pre-rendering for now, the time we found the right way to fix this.

**Comment by obiot** [comment]
just realised as well that the preRender mode will probably not work as well with the new flex scaling mode, we might force-disable it in that case (as we do for animated tiles)

**Comment by obiot** [comment]
this one is fixed, but I'm keeping it open, as there are still a few things i would like to check/do later when I'm back at home (some further optimisation, and maybe some variables name cleaning)

**Comment by obiot** [comment]
i'm happy about it now ! :P

**Comment by aaschmitz** [comment]
Tested and worked, thanks!
