### ISSUE TITLE
Support loading multiple levels

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#704]
Following the redesign of the TMX Map object (#669), we still need to go a bit further to fully support this :
- Change the way we load levels, as for now, when automatically loaded, a level is centered into the viewport
- Change the `flatten` option, that is false by default
- Fix the imageLayer to clip it to the level (seems to be clipped to the viewport for now)
- Test it

**Comment by parasyte** [comment]
@obiot I don't like the name of this ticket. ;P But the rest of it sounds great!

We don't want to stuff multiple levels into the same container. We want to load multiple levels (simultaneously) into their own containers:

```
└── rootContainer
    ├── mapContainer1
    └── mapContainer2
```

Container positioning will be important, but I don't think we should worry about how the containers are positioned; let user code do that. We can fix the auto-center issue with a simple check:

```javascript
if (container === me.game.world) {
    // Center the world container
}
```

The `flatten` options doesn't matter IMHO. Since we need separate containers for each map anyway... The map containers will be pretty opaque; melonJS shouldn't care how objects are organized in them.

Finally, excellent point on the ImageLayer. I originally wanted to clip it to the world, but that will change the way maps are rendered:

* `ImageLayer will then no longer be rendered in screen coordinates. (It will be like this older version: https://github.com/melonjs/melonJS/blob/ceb9cf5af91bff4f8c0bdc8a485e38cae2f1546b/src/level/TMXLayer.js#L230-L259)
* `ColorLayer` needs the same clipping and render in world coordinates. (Multiple maps with different background colors.)
* When `ColorLayer` stops acting as the "clear screen" method, we need to add this functionality into `me.video.renderer.prepareSurface()` -- we already have a `clearSurface()` method for it.

**Comment by obiot** [comment]
Just to clarify what is `flatten` currently doing ;

for the title, feel free to change it :P

when `false`
```
└── rootContainer
    └──mapContainer1
        └── Layer 1
        └── Layer 2
        └── Object 1
    └── mapContainer2
        └── Layer 1
        └── Layer 2
        └── Object 1
```

when `true`
```
└── rootContainer
    ├── Layer 1-1 (mapContainer1)
    ├── Layer 1-2 (mapContainer1) 
    ├── Object 1-1 (mapContainer1)
    ├── Layer 2-1 (mapContainer2)
    ├── Layer 2-2 (mapContainer2)
    └── Object 2-1 (mapContainer2)
```

**Comment by parasyte** [comment]
Oh, if that's the case... this is what it *should* be doing:

(Gotta go a bit deeper to illustrate...)

When `false`:

```
└── rootContainer
    ├── mapContainer1
    │   ├── ImageLayer1
    │   ├── TileLayer1
    │   └── ObjectGroup1
    │       ├── Object1
    │       └── Object2
    └── mapContainer2
        ├── ImageLayer1
        ├── TileLayer1
        └── ObjectGroup1
            ├── Object1
            └── Object2
```

When `true`:

```
└── rootContainer
    ├── mapContainer1
    │   ├── ImageLayer1
    │   ├── TileLayer1
    │   ├── Object1
    │   └── Object2
    └── mapContainer2
        ├── ImageLayer1
        ├── TileLayer1
        ├── Object1
        └── Object2
```

Flatten the object groups within the destination container. That's what I mean by "opaque"; the internal structure within the container doesn't matter, it may or may not have object groups, paperdolls, or whatever else.

**Comment by obiot** [comment]
oups, sorry, you are right about the first one, i just forgot to add the objectGroup level :P

for the second one, it's depends what "target" container you give to the [`addTo`](https://github.com/melonjs/melonJS/blob/master/src/level/TMXTiledMap.js#L438) function, if `flatten` and the same container you could do :


```
└── rootContainer
    ├── ImageLayer1
    ├── TileLayer1
    ├── Object1
    ├── Object2
    ├── ImageLayer1
    ├── TileLayer1
    ├── Object1
    └── Object2
```

**Comment by parasyte** [comment]
Just read through the code in `me.TMXTileMap.getObjects()` and it already does what I described. That's perfect. :smile:

**Comment by obiot** [comment]
:)

**Comment by parasyte** [comment]
Using the same target container multiple times won't work, BTW. The loader needs to start with an empty container. It even clears the container just to be sure.

**Comment by parasyte** [comment]
Any thoughts on what's left to do for this ticket? I think all of my concerns have been resolved. Also tagging these commits:

* 2f32b07c9c32467eb88a3f22ff9d22dcd449aaee
* 6e7b5dce7bd7c5b124392e4688c6ee3ab42a72fb
* e7fc1decd52255c7e3c7e111a64ee4c0eaa17409

**Comment by obiot** [comment]
For me we can close it, it seems to be all there so far, although the true test will be once this will be used for real in a project. 

Do we need an example that loads multiple levels?

**Comment by parasyte** [comment]
Probably! :)

I used it for testing #138 in this thread: https://groups.google.com/d/msg/melonjs/fAtFFe2wvCo/ssIrA2MuAwAJ A proper example would be nice though. I bet we could come up with a fun idea for platformer2, like a random castle map...
