### ISSUE TITLE
Add support for layer data encoding in JSON

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#739]
Tiled added layer data encoding (e.g. Base64) to the JSON map format, and melonJS does not support it. This may be a regression in 3.0.0

This commit reproduces the issue: 2d1658cd41329e8b9a97f746db118fdbcaf94f48

**Comment by obiot** [comment]
this is a quick fix, as a better one would probably to redesign the whole code, but it's doing the trick.

Basically I moved the "decoding" code into a specific function and calling it from 2 places : first from the TMX parser, and then from the `readLayer` function. In case the function was already used to decode data when parsing a TMX file, the encoding is forced to `none`, so that the next time the function does not do anything :P

**Comment by parasyte** [comment]
Hahah! Good enough for now. :)

:+1:

**Comment by obiot** [comment]
good, closing this ticket then ;P
