### ISSUE TITLE
When a container is removed, it does not call deactivate/destroy event callbacks on its children

### ISSUE THREAD

**Issue by agmcleod** [melonjs/melonJS#744]
Removing a container should fire cleanup events for its children. Can either call them directly, or use removeChildNow internally.

**Comment by parasyte** [comment]
Removal should trigger a deactivate event on the children. The destroy event ideally will only be used prior to GC/pushing back to the pool.

This seems like it will fix the removal of entities at every level of the scene graph. But the opposite is also true: inserting into the scene graph needs to defer the activate event until the root node `=== me.game.world`.

**Comment by agmcleod** [comment]
Hmm, think maybe the container calls them manually?

    me.game.world = new me.Container({ root: true });


    // container.js
    onActivateEvent: function () {
      if (!this.root) {
         this.children.forEach(function (c) {c.onActivateEvent()});
      }
    }

**Comment by parasyte** [comment]
Here's a "worst case scenario"

```
root
└── c1
    └── c2
```

There's my current scene graph. Next, I create another sub-tree (in-memory only):

```
c3
└── c4
    └── GUI_Object
```

At this point, the `GUI_Object` should not be activated. Because it's root node is not `me.game.world`

Next, I add this sub-tree to the scene:

```
root
└── c1
    └── c2
        └── c3
            └── c4
                └── GUI_Object
```

GUI_Object gets activated at that point; by adding it as a child of a `c2`!

Seems like each container needs to keep state for whether or not it has been activated. So that when a child is added, it only activates children if it is already active. Is that reasonable?

**Comment by agmcleod** [comment]
Makes sense to me

**Comment by parasyte** [comment]
Yeah, it should be easy enough to implement both, IMO, without much risk.

**Comment by parasyte** [comment]
Small hiccup here: `me.Container` can be added to the scene as an Entity's renderable property! This edge case can be checked for ... but it begs the question whether there are any other cases to consider.

**Comment by obiot** [comment]
seems like this one is done then ?

**Comment by agmcleod** [comment]
Not yet, need to handle adding + activation. That has a bit more work required with it, as jason said we need to only fire it when it's added to the root container, or its parent is added to the root container.

**Comment by obiot** [comment]
do you want to complete this one as part of 3.0.0 or push it to 3.1.0 ?

**Comment by agmcleod** [comment]
Alright, doneskies! 3784982
