### ISSUE TITLE
preRender doesn't work with a WEBGL context

### ISSUE THREAD

**Issue by ldd** [melonjs/melonJS#779]
Please see #661 for more information.

when attempting to clear a tile, I get an error:
```
this.canvasRenderer.clearRect is not a function
```

and when attempting to set a tile after I have set a tile once, I get nothing happening. (tiles can only be set once)

**Comment by obiot** [comment]
interesting !

looks like the following line is totally wrong :
https://github.com/melonjs/melonJS/blob/master/src/level/TMXLayer.js#L585

not only it should be something like `this.renderer.getContext().clearRect(...)` as, `clearRect` is not supported at the renderer "level", but there is not equivalent on the webGL side..... so yes for sure it does not work :(

can you switch off `preRender` at least for the layer where you clear tiles (it can be configured per layer) ?  or is this a blocking point for you ?

**Comment by parasyte** [comment]
Looks like the code was expecting a canvas2d context originally: https://github.com/melonjs/melonJS/commit/1a5cf12637c9ee92de9314cfe33caf4d5ab4dd8f

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/clearRect

**Comment by obiot** [comment]
@parasyte I was thinking: since a `clearRect` is basically the same as `fillRect` with a `(0, 0, 0, 0)` color, can't we use this to easily fake a `clearRect` for the webGL renderer ?

**Comment by obiot** [comment]
I would like also to see is :
- add a proper `me.Renderer.clearRect()` function
- rename the `clearSurface()` function to just `clear()` and just keep the optional `color` and `opaque` parameters (remove the `ctx` one, which by the way is not even used by the webGL `clearSurface` function)
- and while I'm at it, rename also `blitSurface` and `prepareSurface` to `bit` and `prepare` (no need for such a long name, it's obvious enough).

**Comment by obiot** [comment]
few comments on the fix :

- I added a `clearRect` function to both renderer, we already have a `fillRect`, that makes sense API-wise
- preRendering use an offscreen canvas, so the missing clearRect function is really only useful for the CanvasRenderer (and as you can see there is no real changes to the `clearTile` function)
- the WebGLRenderer.clearRect() function might not be super optimised, I leave it as a later exercise, but at least it is working.
- i added an example in the clearTile function, on how to get a reference to each of the level layers, t's always useful to have that somewhere

Left Todo before I close this ticket (if @parasyte agree) :
- rename the `clearSurface()` function to just `clear()` and just keep the optional color and opaque parameters (remove the ctx one, which by the way is not even used by the webGL clearSurface function)
- rename `blitSurface` and `prepareSurface` to respectively `bit` and `prepare`  (no need for such a long name, it's obvious enough).

I don't feel bad about changing these functions, it's certainly breaking the API (which should not be the case for a 3.x.0) release, but considering that these are mostly used internally, it's most certainly invisible for anyone.

**Comment by parasyte** [comment]
> @parasyte I was thinking: since a clearRect is basically the same as fillRect with a (0, 0, 0, 0) color, can't we use this to easily fake a clearRect function for the webGL renderer ?

That depends on the [`globalCompositeOperation`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation). By default it is `source-over` which blends the existing content with the new content; A transparent rect would have the same effect as not drawing at all. `copy` will do what you want, though. We actually use it in a few places, mostly for supporting transparency in the screen canvas:

* https://github.com/melonjs/melonJS/blob/1d959de42ae371a4cb299abf27d942ae1d2b611c/src/video/canvas/canvas_renderer.js#L46
* https://github.com/melonjs/melonJS/blob/1d959de42ae371a4cb299abf27d942ae1d2b611c/src/video/canvas/canvas_renderer.js#L110
* https://github.com/melonjs/melonJS/blob/1d959de42ae371a4cb299abf27d942ae1d2b611c/src/video/canvas/canvas_renderer.js#L285

All that said, we don't have any configuration at the moment for clearing parts of the WebGL frame buffer with a transparent color. We would also have to emulate the `copy` mode by configuring the blend mode and blend function: https://github.com/melonjs/melonJS/blob/cef6ffdfb6059a07b2d2945a1c482fafc0b4db24/src/video/webgl/compositor.js#L188-L190

> few comments on the fix :
>
> * I added a clearRect function to both renderer, we already have a fillRect, that makes sense API-wise

The implementation you added probably won't work, for the reasons above.

> * the WebGLRenderer.clearRect() function might not be super optimised, I leave it as a later exercise, but at least it is working.

Huh... if it is working, that means the renderer is not properly blending, which is problematic.

> I don't feel bad about changing these functions, it's certainly breaking the API (which should not be the case for a 3.x.0) release, but considering that these are mostly used internally, it's most certainly invisible for anyone.

Famous last words! Since these are public methods (and publicly documented), we should do a full version bump on the breaking API changes.

**Comment by parasyte** [comment]
Tested WebGL `clearRect` method with the following simple patch. You can see the difference between canvas and WebGL renderer pretty clearly with this.

```patch
parasyte@Turkatron:~/projects/melonJS (master)$ gd
diff --git a/examples/platformer/js/entities/player.js b/examples/platformer/js/entities/player.js
index 5981ee6..4c2dc26 100644
--- a/examples/platformer/js/entities/player.js
+++ b/examples/platformer/js/entities/player.js
@@ -121,6 +121,11 @@ game.PlayerEntity = me.Entity.extend({
         return false;
     },

+    draw : function (renderer) {
+        this._super(me.Entity, "draw", [ renderer ]);
+
+        renderer.clearRect(this.pos.x, this.pos.y, this.width, this.height);
+    },

     /**
      * colision handler
```

Has no effect on WebGL.

**Comment by obiot** [comment]
> Famous last words! Since these are public methods (and publicly documented), we should do a full version bump on the breaking API changes.

ok yes, you are right, I will leave these changes for after the 3.1.0 release then, no hurry here :)

as for the WebGLRenderer.clearRect function, I will open a specific ticket for it then, since it's not working "as expected".

at least this ticket is fixed, since as I was saying it relies on an offscreen canvas when using pre-rendering.
