### ISSUE TITLE
parsing of CSV encoded data when exporting to JSON is not working

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#788]
melonJS will throw the following exception : `XML encoding is deprecated, use base64 instead`

The issue being that either when using XML or CSV encoding, and then exporting the map to JSON format, the data fields are presented the same way (e.g.  `"data":[12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, ... 12]`) and with the encoding field not set, which then generate the execption

incrimated line here :
https://github.com/melonjs/melonJS/blob/master/src/level/TMXUtils.js#L110

**Comment by parasyte** [comment]
Is this a bug in the Tiled `export JSON` function? It should export the layer encoding information, no?

**Comment by obiot** [comment]
yes and no, i'm not really sure actually, when exporting XML data to JSON, the exporter actually convert it to CSV.

for example taking an imaginary map ,

**TMX Export  :
XML:  `<data> <tile gid="12"/>  <tile gid="12"/>   <tile gid="12"/> ... </data>`
CSV : `"data":[12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, ... 12])`

**JSON Export **
XML : `"data":[12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, ... 12])`
CSV : `"data":[12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, ... 12])`

but now that I wrote it down, I do agree that the encoding field should then be set to CSV in case of JSON export

**Comment by parasyte** [comment]
I see, `encoding` is *only* defined for TMX/CSV. Definitely a Tiled bug. I agree with your original assessment, though; our fault is assuming "XML" when `encoding` is not defined.

The "XML" value could be applied by the XML parser, I guess. Then we assume CSV encoding when undefined. Not ideal, but it will at least be backward compatible with older JSON exported maps (assuming the Tiled bug is fixed in the future).

**Comment by obiot** [comment]
they are a lots of discrepancies between the JSON and TMX format actulally, just already in terms of tag names, as we should not have to "normalize" it on our side in the first place ....

**Comment by obiot** [comment]
great, thanks !

**Comment by parasyte** [comment]
Yes, we could file tickets against those as well. Just not sure what to do about backward compatibility. The only example I can think of at the moment is the `tileproperties` one.

**Comment by bjorn** [comment]
While I'd welcome any effort to document the differences between the TMX and JSON formats, at least for the time being I can't really fix this because it would break backwards compatibility. Even something as simple as removing unnecessary empty `properties` values already leads to people running into issues (http://forum.mapeditor.org/t/save-empty-custom-properties-in-json/1253).

Still, eventually I want to make a clean "TMX 2" format and when I decide to still have both XML and JSON I will try to make them as consistent as possible. Another option would be to use JSON exclusively.
