### ISSUE TITLE
sprite rendering position is off when renderable anchor point is different from [0.5, 0.5]

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#793]
I found this when working on ticket #335, I thought it was a regression in my own [new code](https://github.com/melonjs/melonJS/commit/c30e386a387bfd44e329d23f91e93998c3ce4320), but the issue is also visible on the master branch, and so far I'm clueless on where this is coming from.

reproduce the issue is quite simple, take the texturepacker example and add 

``` javascript
this.renderable.anchorPoint.set(1.0, 1.0); 
```

at the following line 
https://github.com/melonjs/melonJS/blob/master/examples/texturepacker/js/entities/entities.js#L20

Bonus question :
any reason why here 
https://github.com/melonjs/melonJS/blob/master/src/entity/entity.js#L288-L291
we don't rather use _bounds and use something more simple like

``` javascript
var x = ~~( 0.5 + this._bounds.pos.x + (this.anchorPoint.x * this._bounds.width));
var y = ~~( 0.5 + this._bounds.pos.y + (this.anchorPoint.y * this._bounds.height));
```

**Comment by parasyte** [comment]
That code is from: https://github.com/melonjs/melonJS/pull/716

**Comment by obiot** [comment]
correct !

**Comment by Giwayume** [comment]
Looks like I caused all sorts of trouble =P

From what I remember, if you're using texture packer, you _shouldn't_ be setting the sprite's anchor point manually, because the "pivot" point in texture packer controls the sprite's anchor point frame-by-frame.

https://github.com/melonjs/melonJS/blob/master/src/video/canvas/texture.js#L154

If you wanted the sprite's anchor point to be at [1.0, 1.0], you would go back in to texture packer and edit the pivot point there.
