### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by krojew** [melonjs/melonJS#804]
I would be great to add TS typings for melon, and publish them on http://definitelytyped.org/

**Comment by obiot** [comment]
sure, but honestly, unless a motivated contributor appears from nowhere, I don't really see this happening in a near future :)

**Comment by krojew** [comment]
Well, I've been working on this for a few days now :)

**Comment by agmcleod** [comment]
Nice, wish you luck for sure. I've thought about maybe starting to add something like Flowtype, as it can be added bit by bit, and is not as much of an overhaul as typescript would be. Not something i've started or researched at all yet though. I think it does reduce the barrier to entry for contributing a bit, as it can always be added ontop of new additions later, instead of someone being required to know typescript.

**Comment by krojew** [comment]
I've made my first PR regarding this. There's a lot missing, but you get a few thousands lines of typings done :) Unfortunately, I found the official docs are way, way off the actual code. You should really update them.

**Comment by obiot** [comment]
looks like this one is not happening, and there is no real objective to go TS.

**Comment by obiot** [comment]
and this actually finally happen :) thanks to @qpwo and this pull request #1055

@qpwo do you know what the process to then pusblish it on http://definitelytyped.org/ ?

**Comment by qpwo** [comment]
I think you don't have to publish there since the declaration is in the repo. I think definitely typed is for when  contributors can't  reach the original package authors.

And future readers see also  #1056

**Comment by qpwo** [comment]
Hmm some challenges with this. Working on https://github.com/qpwo/melonJS and https://github.com/qpwo/melonjs-typescript-boilerplate … For some reason some of the jsdoc stuff doesn't seem to make it into the declaration files. For example this is all the output of `src/system/device.js` (into `device.d.ts`):

```ts
export default device;
declare namespace device {
    const devicePixelRatio: number;
    const isFullscreen: boolean;
    const sound: boolean;
}
```

Or `unsubscribe` in `src/system/event.js` just becomes a dull `const unsubscribe: any;`.

@obiot What should the approach be? Were you going to refactor some of these objects for the ES6 changes? If so that might make the typescript declarations work without any fuss. Otherwise, I could try moving the jsdocs around a bit to see if I can get them all to pass through.

**Comment by obiot** [comment]
thanks for your hep, I will definitely refactor the remaining old code to es6, will let you know as I progress.

I'll start with `event.js` and `device.js` but if you spot any other small win somewhere, you can go ahead with a pull request :)

**Comment by qpwo** [comment]
This command may also be useful to you, depending on how far you want to go down the typescript compatibility rabbit hole:

```bash
npm exec tsc --allowJs --checkJs --noEmit src/**/*.js
```

See here: https://medium.com/@trukrs/type-safe-javascript-with-jsdoc-7a2a63209b76

**Comment by obiot** [comment]
thanks ! I'm not sure I want to go that far to be honest, my target is at least to get the declaration file to be correct. I'm kind of enjoying the ride though as it makes me realize (or reminds) me or some bad design choice that I'm then taking the opportunity to fix :)
