### ISSUE TITLE
Remove IE9/IE10 support and other legacy browser

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#829]
That includes :
- [x] deprecated / non-standard mousewheel events
https://developer.mozilla.org/en-US/docs/Web/Events/mousewheel
- [x] support for MS prefixed PointerEvent : https://github.com/melonjs/melonJS/blob/master/src/input/pointer.js#L121-L130
- [x]  Array.forEach polyfill :
https://github.com/melonjs/melonJS/blob/master/src/lang/array.js#L29-L40
http://caniuse.com/#search=forEach
- [x]  Array.isArray polyfill :
https://github.com/melonjs/melonJS/blob/master/src/lang/array.js#L42-L53
http://caniuse.com/#search=isArray
- [x] ~~TypedArray polyfill~~ : (ES6)
https://github.com/melonjs/melonJS/blob/master/src/lang/array.js#L98-L146
http://caniuse.com/#search=TypedArray
- [x] Function bind polyfill : (partial support in older version of android < 4.3)
https://github.com/melonjs/melonJS/blob/master/src/lang/function.js#L14-L59
http://caniuse.com/#search=Function.prototype.bind
- [x] Object defineProperty polyfill :
https://github.com/melonjs/melonJS/blob/master/src/lang/object.js#L15-L38
http://kangax.github.io/compat-table/es5/#test-Object.defineProperties
- [x] Object Create polyfill :
https://github.com/melonjs/melonJS/blob/master/src/lang/object.js#L40-L62
http://kangax.github.io/compat-table/es5/#test-Object.defineProperties
- [x] ~~Object is Polyfill~~ (ES6) :
https://github.com/melonjs/melonJS/blob/master/src/lang/object.js#L64-L102
http://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.is
- [x] ~~Object.assign~~ (ES6) :
https://github.com/melonjs/melonJS/blob/master/src/lang/object.js#L104-L152
http://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign
- [x] ~~Date Performance polyfill~~ : (not supported by opera mini, and android < 4.2, might need to be extended to support webworkers)
https://github.com/melonjs/melonJS/blob/master/src/lang/performance.js#L23-L39
http://caniuse.com/#search=performance
https://developer.mozilla.org/en-US/docs/Web/API/Performance/now
- [x] Date now :
https://github.com/melonjs/melonJS/blob/master/src/lang/performance.js#L12-L21
http://kangax.github.io/compat-table/es5/#test-Date_methods_Date.now
- [x] String trim :
https://github.com/melonjs/melonJS/blob/master/src/lang/string.js#L15-L31
http://kangax.github.io/compat-table/es5/#test-String_properties_and_methods_String.prototype.trim

**Comment by obiot** [comment]
nice list to start with, before proceeding, please have a quick review, and strike items that we need to keep, or add anything missing

**Comment by parasyte** [comment]
I was just looking over the [Edge release history](https://en.wikipedia.org/wiki/Microsoft_Edge#Release_history). Microsoft has already released *3 major (public) versions* of the new browser. And since IE11 hasn't been updated in **3 years**, I vote we drop support for it entirely.

For further evidence that retaining IE11 support is a bad idea, I point to Microsoft's [IE End of Support](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support) article, which claims IE11 will stick around and remain supported for the lifetime of the OS on which it is installed. IE11 ships with Windows 10, which itself has a support lifetime lasting until *at least* [October 2020](https://support.microsoft.com/en-us/lifecycle/search?alpha=Windows%2010).

We cannot hold ourselves back for the next 4 years because *IE11*. It's time to drop this piece of crap like the ... piece of crap it is!

Besides, if anyway *really* wants to use melonJS on IE11, they can just use an older version of melonJS...

**Comment by parasyte** [comment]
By the way, Android browser is dead (replaced by Chrome) and Opera Mini is a server-side browser, much like Amazon Silk. We shouldn't care about those platforms; they can't run games anyway. For more info, see: https://dev.opera.com/articles/opera-mini-and-javascript/

On iOS, Opera Mini does have an option called "Turbo Mode" which just changes the server-side rendering into a GUI for iOS WebKit. See: https://dev.opera.com/blog/opera-mini-8-for-ios/#turbo-mode So it has the same feature footprint as the native Mobile Safari.

Opera **Mobile** is a completely different browser altogether, and is powered by Blink and v8, the same rendering engine and JavaScript engine used in Chrome and Desktop Opera... And it is not supported on iOS because Apple's App Store guidelines explicitly disallows these engines. You can get Opera Mobile on Android and Windows Phone.

**Comment by obiot** [comment]
great, so let's drop all these shit for the next major release (aka 5.0), and for those that still need compatiblity with older platforms, they can still use any es5 shim :
https://github.com/es-shims/es5-shim

**Comment by obiot** [comment]
would be a nice anouncement on the blog by the way, 2017 we drop the dead bodies :)

**Comment by parasyte** [comment]
`\o/`

**Comment by obiot** [comment]
we need to get this up-to-date as well, with the minimum version we then support :
http://melonjs.org/#compatibility

**Comment by obiot** [comment]
I spent some time looking at what would be our new browser version minimum requirements, and it then gives the following table :
![image](https://cloud.githubusercontent.com/assets/4033090/22103223/93577e68-de3a-11e6-9a0a-cf3583e568bf.png)

as a reminder, the previous requirement was :

Browser	Version	Status
Chrome	12+	
Safari	5.0+	
Firefox	4+	
Opera	11.00+	
IE	9+	
CocoonJS	2.0+	
Chrome for Mobile	?	
iOS Safari	6+

**Comment by parasyte** [comment]
FWIW https://github.com/melonjs/melonjs.org/commit/b7759d7aac02680c3062191c46f1206c306f98f5 😄

**Comment by obiot** [comment]
18 to 55 seems to be quite a jump for chrome mobile... I wonder if did not check the wrong chrome

**Comment by parasyte** [comment]
`PointerEvent` and `string.trim` are ES6, and were added in Chrome 55.

**Comment by kibertoad** [comment]
I can lend a hand with this. I presume we'd want unit tests running at least on Chrome and Firefox to make sure we didn't get regressions; https://github.com/melonjs/melonJS/pull/890 adds Chrome execution, Firefox would be easy too.

Probably a good place to start would be to add code coverage reports and check what places that use obsolete code are not under test, start with tests, proceed with replacement.

Comments?

**Comment by obiot** [comment]
that would be great, help is always appreciated/awesome :)

Probably they could be added in this test unit :
https://github.com/melonjs/melonJS/blob/master/tests/spec/shim-spec.js

i'm not sure though about the browser and browser version to use, as regression are more likely to happen WHEN using a polyfill ?

**Comment by obiot** [comment]
ticket closed. I doubt it's really useful actually, but I also added some test coverage for these es5 polyfills we removed.
