### ISSUE TITLE
WebGL / Canvas return true ambiguity 

### ISSUE THREAD

**Issue by Dillybob92** [melonjs/melonJS#839]
Return statement in question:

`return this._super(me.Entity, 'update', [dt])`

If you use that for the WebGL Renderer, it makes the game extremely laggy when the **viewport is moving**.

If you use that for the CANVAS Renderer, **no problems, game doesn't lag**.

To fix the WebGL Render lag movement, you need to do, or have a entity somewhere that has return true....

```
this._super(me.Entity, 'update', [dt])
return true;
```
Just a heads up, I spent 3 + hours isolating this and I think it's important to note this in the docs somewhere.....

For example:

http://melonjs.github.io/tutorial-platformer/

Look here:
```
    // return true if we moved or if the renderable was updated
    return (this._super(me.Entity, 'update', [dt]) || this.body.vel.x !== 0 || this.body.vel.y !== 0);
```

This will not work for WebGL

**Comment by agmcleod** [comment]
Basically if false is returned it's causing the game to lag. If that's reproducable with the tutorial as is, i'd like to check it out and see why. The game should only re-render stuff when update returns true, so it could be that it just doesn't update it as often.

**Comment by Dillybob92** [comment]
Looks like the platformer code actually has it correct: https://github.com/melonjs/melonJS/blob/master/examples/platformer/js/entities/player.js#L117

```
            this._super(me.Entity, "update", [dt]);
            return true;
```

I was following the tutorial here [here](http://melonjs.github.io/tutorial-platformer/) though, and they only have `return this._super(me.Entity, "update", [dt]);` which for WebGL will cause the lag. Only if you don't have anything else that returns true though.  (Which that tutorial doesn't)

**Comment by parasyte** [comment]
The platformer example has a default animation (a walk cycle) gated on the entity's velocity. E.g. when you jump (the entity moves vertically) the walk cycle animation plays. Have another look at the condition: https://github.com/melonjs/melonJS/blob/master/examples/platformer/js/entities/player.js#L114-L115

The tutorial doesn't do that: http://melonjs.github.io/tutorial-platformer/#part3

The default animation in the tutorial is *always* updated (calling `this._super(me.Entity, 'update', [dt])`); If the return value is true, it is returned. Otherwise the boolean result of `(this.body.vel.x !== 0 || this.body.vel.y !== 0)` is returned.

`me.Entity.update()` returns true only if the animation state machine has advanced, which is *not* every frame. And of course, the other boolean is only true if the entity is moving...

Now try the actual tutorial snapshot with the WebGL renderer: http://melonjs.github.io/tutorial-platformer/tutorial_step3/index.html#webgl

Notice anything? There's nothing moving... So your GPU isn't redrawing frames. As soon as you push the left or right arrows ... the player entity moves, and the frame redraws. There's no "lag" anywhere. The tutorial is super basic. It's *impossible* for it to have any frame rate issues on WebGL.

**If you have modified the game beyond what's shown in the tutorial, and thereby experiencing "lag" ... then it must be a bug you've introduced.** The common source of this kind of error is adding new custom entities that do not return `true` when their animations or positions are updated. The equally common workaround is to redraw every frame by forcing any entity to always return true. IMHO, this is a bad practice.
