### ISSUE TITLE
Documentation error: me.audio.fade

### ISSUE THREAD

**Issue by krojew** [melonjs/melonJS#853]
Docs say:

param {Number} [**id**] the sound instance ID. If none is passed, all sounds in group will fade.

actual:

function (sound_name, from, to, duration, **instance_id**)

**Comment by krojew** [comment]
Also with mute() and unmute().

**Comment by krojew** [comment]
and some others...

**Comment by parasyte** [comment]
Sometimes we provide different parameter names for public documentation vs the names provided in the code. This doesn't matter because the function gets random (shortened) param names after minification.

This will matter when we start using more ES6, especially with optional named parameters and the like.

**Comment by obiot** [comment]
agree, it does not really matter what are the argument names in the documentation.

does it give you any trouble with TS ?

**Comment by krojew** [comment]
Nope, it doesn't give me any trouble, but it rather looks confusing when the docs are not in sync with the actual code. I'm doing that TS rewrite and the docs help in determining the types of things. From a user perspective - this _might_ not be a problem.
