### ISSUE TITLE
Unused/undocumented skipAutoInit

### ISSUE THREAD

**Issue by krojew** [melonjs/melonJS#857]
me.skipAutoInit is unused anywhere besides window.js. It's also undocumented, so probably a piece of dead code.

**Comment by parasyte** [comment]
It was added a few years ago to allow asynchronous loaders to work: #442

Never got documented, because it wasn't really an "official feature".

**Comment by obiot** [comment]
so i close this one, or should we document it ?

**Comment by krojew** [comment]
If you want to switch to npm, I recommend removing it and deprecating automatic initialization. Things that are done automatically are usually bad when used with modules, and people will want having full control of what happens and when.

**Comment by parasyte** [comment]
That isn't necessarily true. Almost every module hosted in npm does some form of initialization when the module is loaded. The only difference, I suspect, is that you're under the impression that the melonJS initialization sequence is destructive or somehow "dirty". It really isn't any worse than any initialize-on-load done in most other npm modules; It just play nicely with asynchronously loading individual source code files. And this flag was introduced as a workaround for async loading.

Assuming we move to npm and ES6 modules (not commonJS, there's no point to that now) we will have to properly solve the module dependency problem, instead of attempting async module resolution. The flag can be removed when the workaround has been invalidated. melonJS can continue to auto-initialize. And no one will be the wiser.

**Comment by krojew** [comment]
So maybe it's good to document it if someone stumbles upon this problem? If using Webpack or TS, the module dependency problem becomes non-existent, so I don't know if that's something you should really worry about.

**Comment by obiot** [comment]
https://github.com/melonjs/melonJS/commit/5a68571e09391a10f5cd5adf5764785a0e6938a2
