### ISSUE TITLE
Gamepads with low polling rates have axes stuck

### ISSUE THREAD

**Issue by jdkendall** [melonjs/melonJS#880]
#### Expected behavior
Shifting quickly between opposite directions on an axis (up to down, left to right) should register the old axis direction as unpressed and the new axis direction as pressed.

#### Actual behavior
On slower polling controllers (like the SFC30 on Linux) the MelonJS engine sometimes does not catch an intermediary 0 state that unpresses the old axis direction before pressing the new axis direction.

#### Steps to replicate (should work with any controller)
- Hold one direction on an axis on the gamepad.
- Trigger a breakpoint at line 285 of `src/input/gamepad.js` (final line of binding axes iteration function)
- While breakpoint is stopping code, release direction and press opposite direction on same axis
- Resume code

If done correctly, the engine will report both directions as being pressed, with the only solution to release the axis back below the pressed threshold.

**Comment by obiot** [comment]
interesting finding ! 

Quick question  : as the gamepad status is updated along with the frame update, is this something you experienced during a low framerate time, or is this irrelevant to the framerate ?

**Comment by jdkendall** [comment]
When tested it was during normal framerate (didn't measure, but certain it was well over 60fps as I wasn't rendering anything but a small sprite to test gamepad controls.) I'm unsure if framerate timing would have this affect faster polling controllers or not - I imagine at particularly low FPS it would probably happen even to fast polling controllers since the frames where the stick is within the deadzone threshold would possibly be missed.

**Comment by parasyte** [comment]
melonJS doesn't poll the gamepad ... :( The browser does! The only thing melonJS can do is retrieve a snapshot of the gamepad button/axis states every frame.

https://www.w3.org/TR/gamepad/#navigator-interface-extension

> Retrieve a snapshot of the data for the the currently connected and interacted-with gamepads.

It's really the browser that has to poll the hardware/driver. We can only see what the browser provides us.

**Comment by jdkendall** [comment]
That's right, but an axis can only be in one of three states as far as MelonJS is concerned, right? - deadzone, -1, or +1. Currently, if you swap from -1 to +1 too fast, MelonJS believes the axis is both in -1 and +1 state at the same time.

**Comment by parasyte** [comment]
Not quite! That's only true for mapping an axis to a keyboard key. The conversion from analog value to digital value is fully configurable:

* [Add a custom axis normalization callback via remapping](http://melonjs.github.io/melonJS/docs/me.input.html#setGamepadMapping)
  * [normalization function definition](http://melonjs.github.io/melonJS/docs/me.input.html#~normalize_fn)
* [Set the axis threshold to a sane value when binding the axis to a key](http://melonjs.github.io/melonJS/docs/me.input.html#bindGamepad)
* [Set the deadzone for gamepad axes](http://melonjs.github.io/melonJS/docs/me.input.html#setGamepadDeadzone)

You will receive the raw analog value in the normalize function so that it can be normalized to [0..1] if needed, and the other two configurable values specify the conversion logic. It's unlikely that you need to adjust the deadzone, but it's configurable just in case. The important one is the threshold ... and it requires a normalized value.

Anyway, these configurations together allow you to support any weird gamepad you can imagine. Have a look at the [Ouya controller mapping](https://github.com/melonjs/melonJS/blob/22401642a0e35ddcacfff5a62e5909ae30b4ab3a/src/input/gamepad.js#L37-L59) for an insane example; I'll bet the SFC30 is a piece of cake in comparison.

**Comment by jdkendall** [comment]
The issue here is specifically with the mapping to a key, not with the device's configurations re: deadzone etc. I may not have been clear regarding that in my initial post, sorry. :) I'm just doing basic binding to arrow keys like so:

```
        me.input.bindGamepad(0, {type: "axes", code: me.input.GAMEPAD.AXES.LX, threshold: -0.5}, me.input.KEY.LEFT);
        me.input.bindGamepad(0, {type: "axes", code: me.input.GAMEPAD.AXES.LX, threshold: 0.5}, me.input.KEY.RIGHT);
        me.input.bindGamepad(0, {type: "axes", code: me.input.GAMEPAD.AXES.LY, threshold: -0.5}, me.input.KEY.UP);
        me.input.bindGamepad(0, {type: "axes", code: me.input.GAMEPAD.AXES.LY, threshold: 0.5}, me.input.KEY.DOWN);
```

**Comment by parasyte** [comment]
@jdkendall You got me reviewing the code, and you're right. There's a tristate in the edge detection logic because it doesn't handle the opposite axis when `pressed` is true (only when it's false): https://github.com/melonjs/melonJS/blob/22401642a0e35ddcacfff5a62e5909ae30b4ab3a/src/input/gamepad.js#L275-L281

This looks tricky to solve since we have two different mappings to deal with (one for negative values and another for positive).

**Comment by jdkendall** [comment]
I've been messing with it locally, if I come up with anything I'll submit a PR. My free time is limited so it may not happen until this weekend however. :)

**Comment by parasyte** [comment]
@jdkendall I've committed a patch to a new branch. Please try it out when you have a chance: https://melonjs-builds.s3.amazonaws.com/artifacts/bug/ticket-880/1980/build/melonJS.js

I was able to repro the tristate by flicking the analog stick on my PS3 controller quickly. The patch fixes it for me.

**Comment by jdkendall** [comment]
You work fast, @parasyte ! Looks good to me, just tested it out and my gamepad is working flawlessly now. Thank you! :)

**Comment by parasyte** [comment]
Thanks for the report! Sorry it took so long for me to understand what you were experiencing.
