### ISSUE TITLE
WebGL context creation issue on Linux

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#982]
#### OS platform / Browser  
Linux Kubuntu / Chrome & Firefox
 
#### melonJS version 
7.x (since 7.0 melonJS will default to the WebGL renderer, as opposed to the canvas one in the past)

#### Bug description  
On some linux configuration, WebGL context will fail and fallback to canvas

#### Steps to reproduce the bug
launch any game on Linux

#### Console log Extract 
````
Error creating WebGL renderer :
0:2(12): warning: extension `GL_ARB_gpu_shader5' unsupported in fragment shader
0:21(29): error: sampler arrays indexed with non-constant expressions are forbidden in GLSL 1.30 and later
````

**Comment by parasyte** [comment]
I had a similar problem a few years ago with iOS. The solution was to [stop indexing texture samplers](https://github.com/blipjoy/lovelydrive/commit/89b15e6fa451040e3245dba0d6d12830907342d6). :(

**Comment by glm4610** [comment]
It seems that the solution in https://github.com/melonjs/melonJS/commit/72ca0aa3104315dfd8c128d9e5a9c9cd5aaefcad isn't enough.
It isn't safe from the cases where `new WebGLRenderer(...)` might throw an exception _after_ calling `canvas.getContext("webgl")`.

In my case, `new WebGLRenderer` instantiates a `new Compositor`, which instantiates a `new QuadGLShader`. This last guy throws the `GL_ARB_gpu_shader5 unsupported` exception during shader compilation. 

Since this is only thrown after

https://github.com/melonjs/melonJS/blob/4b283edaf9106c06b7209332d6b166521b5ae863/src/video/webgl/webgl_renderer.js#L39

during `WebGLRenderer` initialisation,
then `autoDetectRenderer`'s fallback to
https://github.com/melonjs/melonJS/blob/9cdc0d25dcba103d9c04d37cbb825de9eb838a52/src/video/video.js#L52
will still fail when it tries to get the context through `getContext2d` with the same canvas object.

**Comment by obiot** [comment]
> will still fail when it tries to get the context through getContext2d with the same canvas object.

indeed in that case the existing canvas should be removed from the DOM, and a new one created !

**Comment by obiot** [comment]
the latest commit will now allow to to properly fallback to the canvas renderer when the WebGL one is not able to compile the built-in shaders.

test build here :
https://melonjs-builds.s3.amazonaws.com/artifacts/master/2582/build/melonjs.js

small warning though : as this one was added on the 8.0 branch (major version increase, so some breaking changes) where  we revamped a bit the physic implementation to be closer to those physic engine out-there (with the will to be able to use one of them through a plugin) and as a consequence we now have a world global gravity settings that can then be lowered or amplified per physic object (instead of previously where each object gravity were managed separately), see here for the detailed changes : https://github.com/melonjs/melonJS/wiki/Upgrade-Guide#71x-to-800

**Comment by obiot** [comment]
this is all done !

as per the latest commits melonJS does not pre-index texture samplers anymore, which should increase WebGL compatibility on Linux, and the WebGL renderer will also properly fallback to canvas if failing to compile a shader (which address the unsupported extension exceptions on some older cards).

test build here for those interested, but this is part of the master 8.0 branch :
https://melonjs-builds.s3.amazonaws.com/index.html?prefix=artifacts/master/2597/build/
