### ISSUE TITLE
Creating atlas through code

### ISSUE THREAD

**Issue by devnewton** [melonjs/melonJS#984]
I try to figure how to use some spritesheet ( like https://jb3.devnewton.fr/pasted/2da929eb-8783-4162-87a2-80ac4350ab81.jpg ).

Is it possible to define the atlas manually? Melonjs documentation only talk about Texture Packer or Shoebox.

I tried this:

```
        let atlas = {
            "meta": {
                "app": "melonJS",
                "size": {"w": 512, "h": 512},
                "repeat": "no-repeat",
                "image": "sara"
            },
            "frames": [{
                    "filename": "stand",
                    "frame": {"x": 1, "y": 1, "w": 32, "h": 48}
                }]
        };

       let texture = new me.video.renderer.Texture(
                atlas,
                me.loader.getImage("sara")
                );
        this.renderable = new me.Sprite(0, 0, {image: texture});
        this.renderable.addAnimation("stand", [{ name: "stand", delay: Infinity }]);
        this.setCurrentAnimation("stand");
```

But it is not detected as an atlas:

> string parameters for addAnimation are not allowed for standard spritesheet based Texture

**Comment by obiot** [comment]
when creating sprite out of atlas, you should rather use the "createAnimationFromName" helper function : 
http://melonjs.github.io/melonJS/docs/me.Renderer.Texture.html#.createAnimationFromName

so you should change the renderable definition to :
```javascript
this.renderable = texture.createAnimationFromName(["stand"]);
this.renderable.addAnimation("stand", [{ name: "stand", delay: Infinity }]);
this.renderable.setCurrentAnimation("stand");
```
(also, be careful, you call `setCurrentAnimation` on `this` object instead of the renderable)

this should helpfully work now :P
