### ISSUE TITLE
DebugPanel state alters behavior of setCurrentAnimation

### ISSUE THREAD

**Issue by Hectate** [melonjs/melonJS#988]
If you are submitting a bug report, please respect the below template :

#### OS platform / Browser  
Windows 10, Firefox 75.0 (64 bit)
 
#### melonJS version 
6.0.0 (I just realized that this is an old version because I started from ``boilerplate``)

#### Bug description  
Updates to an entity's animation are different if DebugPanel is active than when it is not. Specifically:
* If DebugPanel is displayed, using ``setCurrentAnimation()`` will change the visible animation immediately.
* If DebugPanel is not displayed, using ``setCurrentAnimation()`` will not change the animation immediately. It appears to delay it until the current frame duration is elapsed.

#### Steps to reproduce the bug
* Download and extract the attached project (based off boilerplate). Use ``npm install`` and ``grunt serve`` to launch to https://localhost:8000
* With DebugPanel disabled (default state) press Z and X to switch between animations ``one`` and ``two``. Note that the 1000ms frame duration of the current animation is not interrupted.
* Press ``S`` to enable DebugPanel.
* With DebugPanel enabled, press Z and X to switch between animations ``one`` and ``two``. Note that the animation is changed immediately, regardless of any remaining frame duration for the current animation.

[boilerplate.zip](https://github.com/melonjs/melonJS/files/4462682/boilerplate.zip)

**Comment by Hectate** [comment]
I updated my files to ``7.1.1`` and the behavior did not change; except possibly the frame itself is not reverting to the first automatically now. Unsure if this is normal behavior.

**Comment by obiot** [comment]
interesting bug !!!

about 7.x, have you also updated the debug panel ?

https://github.com/melonjs/melonJS/releases/tag/7.1.1

**Comment by Hectate** [comment]
Yes, I downloaded both, put them into the boilerplate, and repeated the tests. Confirmed version of melonJS had updated in the console log. I don't see a version for the ``debugPanel.js`` but I had acquired it from the releases page at the same time because it was available there.

**Comment by obiot** [comment]
ok so I think I know how to explain this.

First couple of things to consider : 

- `setCurrentAnimation()` change the animation right away, the optional delay parameter is the delay between the defined frame for the defined animation.
-  melonJS only refresh (redraw) the screen if at at least one object returns true from its `update()` function. this is also explained [here](https://github.com/melonjs/melonJS/wiki/MelonJS-Core) if you are interested, although the wiki is not really up-to-date, but that's the basic of it.

Therefore, looking at your example :

1. with the debugPanel visible, screen is refreshed (redraw) at every frame since the debug panel is enforcing that to display framerate, etc...
2. with the debugPanel not visible, it's only based on the value returned by the update method of your object, which appears to be `false` most of the time here, change it to `return true` and the setCurrentAnimation will (visually) change right away as well

**Comment by Hectate** [comment]
So what I gather from your post is that if I want to have my animations change immediately, I need to keep track of the update status and return that at the end (e.g. if I changed animation return ``true``). Notably, the code already does this with the velocity of the entity, but not if the entity has no velocity; which was the case for changing animations while standing still.

**Comment by obiot** [comment]
the code you mentioned here will return true both if the sprite animation was updated, and if the entity physics was updated, but for the renderable part I'm afraid the sprite update function is not able to identify if the current animation was modified, have a look here:
https://github.com/melonjs/melonJS/blob/166eb28e6aac09741f1458913c822a819ee21d81/src/renderable/sprite.js#L507

**Comment by obiot** [comment]
this should be now properly fix in the 8.0 branch, thank you !

**Comment by obiot** [comment]
FYI I also updated the boilerplate, thanks for the reminder :)
