### ISSUE TITLE
Random error: Cannot read property containsPoint of undefined

### ISSUE THREAD

**Issue by siauderman** [melonjs/melonJS#996]
I am getting this random error which sometimes freezes my app

melonjs.js?22b4:24982 Uncaught TypeError: Cannot read property 'containsPoint' of undefined
    at dispatchEvent (melonjs.js?22b4:24982)
    at HTMLCanvasElement.onMoveEvent (melonjs.js?22b4:25108)

the relevant portion of the code is here:
````
 if (!region.currentTransform.isIdentity()) {
                 var invV = region.currentTransform.multiplyVectorInverse(me.pool.pull("me.Vector2d", gameX, gameY));
                 gameX = invV.x;
                 gameY = invV.y;
                 me.pool.push(invV);
               }

               eventInBounds = bounds.containsPoint(gameX, gameY);
             } else {
               eventInBounds = bounds.containsPoint(pointer.gameX, pointer.gameY) && (bounds === region || // if the given target is another shape than me.Rect ***this is the line that causes the error
               region.containsPoint(pointer.gameLocalX, pointer.gameLocalY));
             }

             switch (pointer.type) {
               case POINTER_MOVE[0]:
               case POINTER_MOVE[1]:
               case POINTER_MOVE[2]:
               case POINTER_MOVE[3]:
````
bounds is set to region.getBounds() earlier in the code. I suspect that there is something causing region.getBounds() to return undefined.

**Comment by siauderman** [comment]
Related error:

melonjs.js?22b4:24973 Uncaught TypeError: Cannot read property 'isIdentity' of undefined
    at dispatchEvent (melonjs.js?22b4:24973)
    at HTMLCanvasElement.onMoveEvent (melonjs.js?22b4:25108)

````
               if (!region.currentTransform.isIdentity()) {
                 var invV = region.currentTransform.multiplyVectorInverse(me.pool.pull("me.Vector2d", gameX, gameY));
                 gameX = invV.x;
                 gameY = invV.y;
                 me.pool.push(invV);
               }
````

**Comment by obiot** [comment]
[registerPointerEvent](http://melonjs.github.io/melonJS/docs/me.input.html#.registerPointerEvent) only accepts shape object (and then any renderable since it derivate from me.Rect) as a target for event, with all shapes object implementing the here above "missing" bounds (obtained by calling `getBounds()`).

what object(s) are u using for event registration ? did you maybe forgot to de-register an event (see [releasePointerEvent](http://melonjs.github.io/melonJS/docs/me.input.html#.releasePointerEvent)) on a specific object that got deleted/recycled.

**Comment by siauderman** [comment]
My pointer events are on Sprites.

Do I have to deregister every single event? Maybe there can be something added to melonjs.me.game.world.removeChild to deregister the events since the child is no longer valid?

**Comment by siauderman** [comment]
Indeed you are right.

I added in handlers to call releasePointerEvent whenever any item is removed and it seems to have stopped one source of the mysterious screen freezes.

**Comment by obiot** [comment]
@siauderman following your suggestion, melonJS will now automatically release any registered event on a renderable, as soon as the object is destroy. 

couple of comments :
- melonJS will attempt to release event based on the renderable instance itself, if something else is used than the object itself it won't work (cannot guess which object was used)
- event released is done from the renderable destroy method, and won't be called (expected behaviour) if the object is [persistent](http://melonjs.github.io/melonJS/docs/me.Renderable.html#.isPersistent)
- as event are now automatically released for object recycling and event registration to work properly, `registerPointerEvent` should not be called from the constructor but from the onResetEvent method or similar

**Comment by siauderman** [comment]
@obiot Yay thanks.
